using FluentMigrator;

namespace OutboxService.Infrastructure.Database.Migrations;

[Migration(20250513-1018)]
public class CreateTable_MyDataChangedOutbox : Migration
{
    public override void Up()
    {
        Execute.Sql(
            @$"
CREATE TABLE IF NOT EXISTS MyDataChangedOutbox (
    Id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    Data TEXT NOT NULL,
    Created TIMESTAMP DEFAULT current_timestamp,
    OccupiedTill TIMESTAMP 
);

CREATE INDEX IF NOT EXISTS
    IDX_MyDataChangedOutbox_Created_OccupiedTill
    ON MyDataChangedOutbox (Created, OccupiedTill);"
        );
    }

    public override void Down()
    {
        Execute.Sql("DROP TABLE IF EXISTS MyDataChangedOutbox;");
    }
}